apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: impsigljc-python 
  janus-idp.io/tekton: impsigljc-python
  backstage.io/kubernetes-id: impsigljc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: impsigljc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  