apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: impsigljc-python-gitops
  description: This is GitOps manifest for impsigljc-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: impsigljc-python
    janus-idp.io/tekton: impsigljc-python 
    backstage.io/kubernetes-id: impsigljc-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:impsigljc-python
